// FIXME Algunos paices estane en ingles
export default [
  { key: '#F44336', text: 'Rojo', color: 'red' },
  { key: '#E91E63', text: 'Rosa', color: 'pink' },
  { key: '#9C27B0', text: 'Violeta', color: 'purple' },
  { key: '#673AB7', text: 'Violeta oscuro', color: 'deep-purple' },
  { key: '#3F51B5', text: 'Indigo', color: 'indigo' },
  { key: '#2196F3', text: 'Azul', color: 'blue' },
  { key: '#03A9F4', text: 'Azul claro', color: 'light-blue' },
  { key: '#00BCD4', text: 'Celeste', color: 'cyan' },
  { key: '#009688', text: 'Teal', color: 'teal' },
  { key: '#4CAF50', text: 'Verde', color: 'green' },
  { key: '#8BC34A', text: 'Verde claro', color: 'light-green' },
  { key: '#CDDC39', text: 'Limón', color: 'lime' },
  { key: '#FFEB3B', text: 'Amarillo', color: 'yellow' },
  { key: '#FFC107', text: 'Ámbar', color: 'amber' },
  { key: '#FF9800', text: 'Naranja', color: 'orange' },
  { key: '#FF5722', text: 'Naranja oscuro', color: 'deep-orange' },
  { key: '#795548', text: 'Marrón', color: 'brown' },
  { key: '#607D8B', text: 'Gris azulado', color: 'blue-grey' },
  { key: '#9E9E9E', text: 'Gris', color: 'grey' },
]
