module.exports.Reset = '\x1B[0m'
module.exports.Bright = '\x1B[1m'
module.exports.Dim = '\x1B[2m'
module.exports.Underscore = '\x1B[4m'
module.exports.Blink = '\x1B[5m'
module.exports.Reverse = '\x1B[7m'
module.exports.Hidden = '\x1B[8m'

module.exports.FgBlack = '\x1B[30m'
module.exports.FgRed = '\x1B[31m'
module.exports.FgGreen = '\x1B[32m'
module.exports.FgYellow = '\x1B[33m'
module.exports.FgBlue = '\x1B[34m'
module.exports.FgMagenta = '\x1B[35m'
module.exports.FgCyan = '\x1B[36m'
module.exports.FgWhite = '\x1B[37m'

module.exports.BgBlack = '\x1B[40m'
module.exports.BgRed = '\x1B[41m'
module.exports.BgGreen = '\x1B[42m'
module.exports.BgYellow = '\x1B[43m'
module.exports.BgBlue = '\x1B[44m'
module.exports.BgMagenta = '\x1B[45m'
module.exports.BgCyan = '\x1B[46m'
module.exports.BgWhite = '\x1B[47m'
